#!/usr/bin/env python3
import pathlib, re

f = pathlib.Path("practice/motions/index.html")
src = f.read_text()

# Full replacement — clean motions only, nothing religion/drugs/death/abortion/guns/race/religion
CLEAN_MOTIONS = """const MOTIONS = [
  {t:"Economic development should be prioritized over environmental protection.",f:"LD",topic:"Economics",level:"Novice"},
  {t:"A just society ought to guarantee universal access to healthcare.",f:"LD",topic:"Social",level:"Novice"},
  {t:"Democratic governments have an obligation to provide free higher education.",f:"LD",topic:"Social",level:"Novice"},
  {t:"Free trade is preferable to fair trade.",f:"LD",topic:"Economics",level:"Varsity"},
  {t:"Civil disobedience in a democracy is morally justified.",f:"LD",topic:"Ethics",level:"Varsity"},
  {t:"Individuals have a moral obligation to obey unjust laws.",f:"LD",topic:"Ethics",level:"Varsity"},
  {t:"When in conflict, a nation's obligation to its own citizens ought to outweigh its obligation to citizens of other nations.",f:"LD",topic:"International",level:"Varsity"},
  {t:"Rehabilitation ought to be valued above punishment in the criminal justice system.",f:"LD",topic:"Justice",level:"Novice"},
  {t:"Democracies ought to require compulsory voting.",f:"LD",topic:"Politics",level:"Novice"},
  {t:"A just government ought to prioritize the needs of future generations over the needs of its current citizens.",f:"LD",topic:"Politics",level:"Varsity"},
  {t:"States ought not possess nuclear weapons.",f:"LD",topic:"International",level:"Varsity"},
  {t:"Freedom of the press ought to be valued above national security.",f:"LD",topic:"Politics",level:"Varsity"},
  {t:"The right to privacy ought to take precedence over the right to the free flow of information.",f:"LD",topic:"Politics",level:"Varsity"},
  {t:"Developed countries have a moral obligation to address climate change.",f:"LD",topic:"Environment",level:"Novice"},
  {t:"Capitalism is a just economic system.",f:"LD",topic:"Economics",level:"Varsity"},
  {t:"The benefits of economic globalization outweigh the harms.",f:"LD",topic:"Economics",level:"Varsity"},
  {t:"Individuals have a moral obligation to engage in political activism.",f:"LD",topic:"Politics",level:"Varsity"},
  {t:"Moral obligations to future generations are as strong as obligations to current generations.",f:"LD",topic:"Ethics",level:"Varsity"},
  {t:"A just society ought to guarantee universal basic income.",f:"LD",topic:"Economics",level:"Novice"},
  {t:"International cooperation is more valuable than national sovereignty.",f:"LD",topic:"International",level:"Varsity"},
  {t:"Justice requires equal outcomes, not merely equal opportunities.",f:"LD",topic:"Ethics",level:"Varsity"},
  {t:"Scientific progress ought to be valued above tradition.",f:"LD",topic:"Science",level:"Novice"},
  {t:"A just society ought to prioritize collective welfare over individual rights.",f:"LD",topic:"Ethics",level:"Varsity"},
  {t:"Government surveillance is justified in the interest of national security.",f:"LD",topic:"Politics",level:"Varsity"},
  {t:"The United States ought to implement universal basic income.",f:"LD",topic:"Economics",level:"Novice"},

  {t:"The United States federal government should substantially reduce its military presence in the Asia-Pacific region.",f:"PF",topic:"International",level:"Varsity"},
  {t:"NATO expansion into Eastern Europe has done more harm than good.",f:"PF",topic:"International",level:"Varsity"},
  {t:"The United States should eliminate subsidies for fossil fuel companies.",f:"PF",topic:"Environment",level:"Novice"},
  {t:"The United States federal government should substantially increase investment in nuclear energy.",f:"PF",topic:"Environment",level:"Varsity"},
  {t:"Artificial intelligence will do more harm than good to the global economy.",f:"PF",topic:"Science",level:"Novice"},
  {t:"The United States should adopt ranked choice voting.",f:"PF",topic:"Politics",level:"Novice"},
  {t:"Universal healthcare in the United States would do more good than harm.",f:"PF",topic:"Social",level:"Novice"},
  {t:"The United States should substantially increase funding for space exploration.",f:"PF",topic:"Science",level:"Novice"},
  {t:"Economic sanctions are an effective tool of foreign policy.",f:"PF",topic:"International",level:"Varsity"},
  {t:"The United States should implement a carbon tax.",f:"PF",topic:"Environment",level:"Novice"},
  {t:"Social media companies should be held legally liable for content posted on their platforms.",f:"PF",topic:"Science",level:"Novice"},
  {t:"The International Monetary Fund does more harm than good.",f:"PF",topic:"Economics",level:"Varsity"},
  {t:"The United States should end the trade embargo on Cuba.",f:"PF",topic:"International",level:"Novice"},
  {t:"Developed nations should open their borders to climate refugees.",f:"PF",topic:"International",level:"Varsity"},
  {t:"The United States federal government should substantially increase its use of economic incentives to address climate change.",f:"PF",topic:"Environment",level:"Varsity"},
  {t:"The World Trade Organization does more harm than good.",f:"PF",topic:"Economics",level:"Varsity"},
  {t:"The United States should substantially reduce its defense budget.",f:"PF",topic:"Politics",level:"Novice"},
  {t:"Cryptocurrency will do more harm than good to the global economy.",f:"PF",topic:"Economics",level:"Novice"},
  {t:"Universal pre-K education would do more good than harm in the United States.",f:"PF",topic:"Social",level:"Novice"},
  {t:"The United States should provide universal access to broadband internet.",f:"PF",topic:"Social",level:"Novice"},
  {t:"The United States should substantially increase foreign aid to developing nations.",f:"PF",topic:"International",level:"Novice"},
  {t:"Automation will do more harm than good to the global workforce.",f:"PF",topic:"Economics",level:"Novice"},
  {t:"The United States should rejoin the Trans-Pacific Partnership.",f:"PF",topic:"Economics",level:"Varsity"},
  {t:"The benefits of the sharing economy outweigh the harms.",f:"PF",topic:"Economics",level:"Novice"},
  {t:"The United States should implement a wealth tax.",f:"PF",topic:"Economics",level:"Novice"},

  {t:"This house would abolish the death penalty worldwide.",f:"BP",topic:"Justice",level:"Novice"},
  {t:"This house believes that social media has done more harm than good.",f:"BP",topic:"Science",level:"Novice"},
  {t:"This house would implement a global carbon tax.",f:"BP",topic:"Environment",level:"Novice"},
  {t:"This house believes that universal basic income is good policy.",f:"BP",topic:"Economics",level:"Novice"},
  {t:"This house would ban political advertising on social media.",f:"BP",topic:"Politics",level:"Novice"},
  {t:"This house would require all citizens to vote.",f:"BP",topic:"Politics",level:"Novice"},
  {t:"This house believes that free trade does more harm than good.",f:"BP",topic:"Economics",level:"Varsity"},
  {t:"This house believes that AI poses an existential threat to humanity.",f:"BP",topic:"Science",level:"Novice"},
  {t:"This house believes that the Internet has done more harm than good.",f:"BP",topic:"Science",level:"Novice"},
  {t:"This house would abolish nuclear weapons.",f:"BP",topic:"International",level:"Novice"},
  {t:"This house believes that capitalism is incompatible with environmental sustainability.",f:"BP",topic:"Economics",level:"Varsity"},
  {t:"This house would implement open borders.",f:"BP",topic:"International",level:"Varsity"},
  {t:"This house believes that democracy is overrated.",f:"BP",topic:"Politics",level:"Varsity"},
  {t:"This house would make voting compulsory.",f:"BP",topic:"Politics",level:"Novice"},
  {t:"This house believes that whistleblowers should be protected by law.",f:"BP",topic:"Politics",level:"Novice"},
  {t:"This house would ban private schools.",f:"BP",topic:"Social",level:"Varsity"},
  {t:"This house believes that richer nations owe a debt to former colonies.",f:"BP",topic:"International",level:"Varsity"},
  {t:"This house would introduce a maximum wage.",f:"BP",topic:"Economics",level:"Varsity"},
  {t:"This house would ban the use of autonomous weapons.",f:"BP",topic:"International",level:"Novice"},
  {t:"This house believes that universal healthcare is a human right.",f:"BP",topic:"Social",level:"Novice"},
  {t:"This house would make higher education free.",f:"BP",topic:"Social",level:"Novice"},
  {t:"This house believes the permanent members of the UN Security Council should lose their veto powers.",f:"BP",topic:"International",level:"Varsity"},
  {t:"This house would tax wealth, not income.",f:"BP",topic:"Economics",level:"Varsity"},
  {t:"This house believes that foreign aid does more harm than good.",f:"BP",topic:"International",level:"Novice"},
  {t:"This house would introduce a four-day working week.",f:"BP",topic:"Economics",level:"Novice"},
  {t:"This house believes that economic growth should no longer be a primary policy goal.",f:"BP",topic:"Economics",level:"Varsity"},
  {t:"This house would give the United Nations binding enforcement powers.",f:"BP",topic:"International",level:"Varsity"},
  {t:"This house believes that nationalism does more harm than good.",f:"BP",topic:"Politics",level:"Varsity"},
  {t:"This house would require large corporations to have employee representatives on their boards.",f:"BP",topic:"Economics",level:"Varsity"},
  {t:"This house believes that the gig economy does more harm than good.",f:"BP",topic:"Economics",level:"Novice"},

  {t:"This house believes that the free market is the best solution to climate change.",f:"WSDC",topic:"Environment",level:"Varsity"},
  {t:"This house would forgive all developing world debt.",f:"WSDC",topic:"Economics",level:"Varsity"},
  {t:"This house believes that the United Nations has failed.",f:"WSDC",topic:"International",level:"Novice"},
  {t:"This house believes that economic sanctions do more harm than good.",f:"WSDC",topic:"International",level:"Varsity"},
  {t:"This house would introduce a Robin Hood tax.",f:"WSDC",topic:"Economics",level:"Novice"},
  {t:"This house believes that the Internet should be a human right.",f:"WSDC",topic:"Science",level:"Novice"},
  {t:"This house would ban fossil fuel advertising.",f:"WSDC",topic:"Environment",level:"Novice"},
  {t:"This house believes that mass surveillance is justified in the fight against terrorism.",f:"WSDC",topic:"Politics",level:"Varsity"},
  {t:"This house believes that democracy is not suitable for all societies.",f:"WSDC",topic:"Politics",level:"Varsity"},
  {t:"This house would give children the right to vote.",f:"WSDC",topic:"Politics",level:"Novice"},
  {t:"This house believes that foreign aid does more harm than good.",f:"WSDC",topic:"International",level:"Novice"},
  {t:"This house would make voting compulsory.",f:"WSDC",topic:"Politics",level:"Novice"},
  {t:"This house believes that private companies should not be involved in space exploration.",f:"WSDC",topic:"Science",level:"Novice"},
  {t:"This house would implement open borders globally.",f:"WSDC",topic:"International",level:"Varsity"},
  {t:"This house believes that the world would be better without intellectual property rights.",f:"WSDC",topic:"Economics",level:"Varsity"},
  {t:"This house would introduce a universal basic income.",f:"WSDC",topic:"Economics",level:"Novice"},
  {t:"This house believes that animals should have legal rights.",f:"WSDC",topic:"Ethics",level:"Novice"},
  {t:"This house would criminalise climate change denial.",f:"WSDC",topic:"Environment",level:"Varsity"},
  {t:"This house believes that the US embargo on Cuba should be lifted.",f:"WSDC",topic:"International",level:"Novice"},
  {t:"This house would require developed nations to accept climate refugees.",f:"WSDC",topic:"International",level:"Varsity"},
  {t:"This house believes that international courts should have jurisdiction over war crimes.",f:"WSDC",topic:"International",level:"Varsity"},
  {t:"This house would ban single-use plastics globally.",f:"WSDC",topic:"Environment",level:"Novice"},
  {t:"This house believes that technology companies have too much power.",f:"WSDC",topic:"Science",level:"Novice"},
  {t:"This house would introduce a global minimum wage.",f:"WSDC",topic:"Economics",level:"Varsity"},
  {t:"This house believes that space exploration should be a global priority.",f:"WSDC",topic:"Science",level:"Novice"},

  {t:"This house believes that free speech should have limits.",f:"Parli",topic:"Politics",level:"Novice"},
  {t:"This house would implement a four-day working week.",f:"Parli",topic:"Economics",level:"Novice"},
  {t:"This house believes that social media influencers should be regulated.",f:"Parli",topic:"Science",level:"Novice"},
  {t:"This house would ban fast fashion.",f:"Parli",topic:"Environment",level:"Novice"},
  {t:"This house would make internet access a public utility.",f:"Parli",topic:"Science",level:"Novice"},
  {t:"This house would ban single-use plastics.",f:"Parli",topic:"Environment",level:"Novice"},
  {t:"This house believes that private healthcare does more harm than good.",f:"Parli",topic:"Social",level:"Novice"},
  {t:"This house would introduce a sugar tax.",f:"Parli",topic:"Social",level:"Novice"},
  {t:"This house believes that online anonymity does more harm than good.",f:"Parli",topic:"Science",level:"Novice"},
  {t:"This house would require corporations to publish their carbon footprint.",f:"Parli",topic:"Environment",level:"Novice"},
  {t:"This house believes that artificial intelligence will create more jobs than it destroys.",f:"Parli",topic:"Science",level:"Novice"},
  {t:"This house would make financial literacy education compulsory in schools.",f:"Parli",topic:"Social",level:"Novice"},
  {t:"This house believes that international trade agreements do more harm than good.",f:"Parli",topic:"Economics",level:"Varsity"},
  {t:"This house would cap executive pay at twenty times the median worker salary.",f:"Parli",topic:"Economics",level:"Varsity"},
  {t:"This house believes that local government should have more power than central government.",f:"Parli",topic:"Politics",level:"Novice"},
];"""

# Replace the MOTIONS array
src = re.sub(r'const MOTIONS = \[.*?\];', CLEAN_MOTIONS, src, flags=re.DOTALL)
f.write_text(src)
count = src.count('{t:')
print(f"ok: {count} clean motions written")
